#!/bin/bash

rm $1.out $1.tmp
$TOCCATA_DIR/new-toc $1 > $1.tmp &&
awk '/^#$/ { printf "#line %d \"%s\"\n", NR+1, "m.c"; next; } { print; }' $1.tmp > m.c &&
emcc -I$TOCCATA_DIR $TOCCATA_DIR/core.c -O1 -DTOCCATA_WASM=1 m.c -s WASM=1 -o $1.js &&
/home/jim/emsdk/node/8.9.1_64bit/bin/node $1.js

# ./$1.out "${@:2}"

# $CC -g -fno-objc-arc -o m -I$TOCCATA_DIR -std=c99 -DCHECK_MEM_LEAK=1 $TOCCATA_DIR/core.c m.c -lpthread && ./m
# $CC -g -fno-objc-arc -o new-toc -I$TOCCATA_DIR -std=c99 -DCHECK_MEM_LEAK=1 $TOCCATA_DIR/core.c new-toc.c -lpthread

