# Makefile for toccata compiler

# Variables
PROJECT_NAME = toccata
VERSION = 1.0.0
CC = clang
CFLAGS = -g -std=c99
LDFLAGS = -lpthread -latomic
TOC_FLAGS = -march=native -I$(pwd) -DCHECK_MEM_LEAK=1 -DSAFETY=1 -DSTATS=1 -lm 
TARGET = $(PROJECT_NAME)

# Default target
.PHONY: toccata
toccata: toccata.c core.c
	@echo "Building toccata"
	$(CC) -O3 $(CFLAGS) -o toccata toccata.c core.c $(LDFLAGS)

# Test1 target
.PHONY: test1
test1.c: new-toc regression-tests/test1.toc
	@echo "Building test1"
	./new-toc regression-tests/test1.toc > regression-tests/test1.tmp
	# sed -i '/if(1){}$/d' regression-tests/test1.tmp
	awk '/^#$/ { printf "#line %d \"%s\"\n", NR+1, "m.c"; next; } { print; }' regression-tests/test1.tmp > regression-tests/test1.c

test1: test1.c new.c runtime3.c
	$CC $(CFLAGS) -o test1 $(TOC_FLAGS) $(LDFLAGS) runtime3.c new.c test1.c

# Help target
.PHONY: help
help:
	@echo "Available targets:"
	@echo "  toccata - Build the base toccata compiler"
	@echo "  test1   - Build and run test1"
	@echo "  clean   - Remove build files"
	@echo "  help    - Show this help message"

# Clean build files
.PHONY: clean
clean:
	rm -f toccata

# Default help if no target specified
.DEFAULT_GOAL := help