#!/bin/bash

set -e

$CC -O3 -g -fno-objc-arc -std=c99 -c core.c &&

git checkout toccata.c &&
$CC -O3 -g -fno-objc-arc -o toccata -std=c99 core.o toccata.c -lpthread &&

time `./toccata toccata.toc > toccata.c`&&
$CC -O3 -g -fno-objc-arc -o toccata -std=c99 core.o toccata.c -lpthread &&

pids=( )
for file in regression-tests/test*.toc
do
   ./test-regression $file & pids+=( $! )
done

for file in assertion-tests/*.toc
do
   ./test-assertion $file 2> /dev/null & pids+=( $! )
done

for file in runtime-tests/*.toc
do
   ./test-runtime-check $file 2> /dev/null & pids+=( $! )
done

for pid in "${pids[@]}";
do
   wait "$pid"
done

time `./toccata toccata.toc > toccata.c` &&
$CC -O3 -g -fno-objc-arc -o toccata -std=c99 core.o toccata.c -lpthread &&

time `./toccata toccata.toc > toccata.c`&&
$CC -O3 -g -fno-objc-arc -o toccata -std=c99 core.o toccata.c -lpthread &&

echo
echo "Regressions pass"
