#!/bin/bash

time ./compiler.toc.out "$1" > q.c &&
clang-format q.c > t.c &&
time $CC -g -I$TOCCATA_DIR -std=c99 \
     -DCHECK_MEM_LEAK=1 \
     $TOCCATA_DIR/runtime.c t.c \
     -lpthread -latomic &&
./a.out
