#!/bin/bash

rm $1.out $1.tmp
echo "using toccata, not new-toc"
cp /home/jim/toccata/good-core.toc /home/jim/toccata/core.toc &&
time $TOCCATA_DIR/toccata $1 > $1.tmp &&
sed -i 's/maybe((FnArity/maybe((Vector/' $1.tmp &&

awk '/^#$/ { printf "#line %d \"%s\"\n", NR+1, "m.c"; next; } { print; }' $1.tmp > m.c &&
time $CC -g -o $1.out -I$TOCCATA_DIR -std=c99 -DCHECK_MEM_LEAK=1 $TOCCATA_DIR/core.c m.c \
     -lpthread -latomic &&
./$1.out "${@:2}"

# $CC -g -fno-objc-arc -o m -I$TOCCATA_DIR -std=c99 -DCHECK_MEM_LEAK=1 $TOCCATA_DIR/core.c m.c -lpthread -latomic && ./m
# $CC -g -fno-objc-arc -o new-toc -I$TOCCATA_DIR -std=c99 -DCHECK_MEM_LEAK=1 $TOCCATA_DIR/core.c new-toc.c -lpthread
# $CC -g -fno-objc-arc -o scripter -I$TOCCATA_DIR -std=c99 -DCHECK_MEM_LEAK=1 $TOCCATA_DIR/core.c scripter.c -lpthread && ./scripter test.toc

