#!/bin/bash

rm $1.out $1.tmp
if [[ -n $1 ]]
then
  time $TOCCATA_DIR/new-toc $1 > $1.tmp &&
  sed -i '/if(1){}$/d' $1.tmp &&
  
  awk '/^#$/ { printf "#line %d \"%s\"\n", NR+1, "m.c"; next; } { print; }' $1.tmp > m.c &&
  time $CC -g -march=native -o a.out -I$TOCCATA_DIR \
       -DCHECK_MEM_LEAK=1 -DSAFETY=1 -DSTATS=1 \
       -lm -lpthread -latomic \
       $TOCCATA_DIR/runtime3.c $TOCCATA_DIR/new.c m.c &&
  time ./a.out "${@:2}"
else
  time $CC -g -march=native -o a.out -I$TOCCATA_DIR \
       -DCHECK_MEM_LEAK=1 -DSAFETY=1 -DSTATS=1 \
       -lm -lpthread -latomic \
       $TOCCATA_DIR/runtime3.c $TOCCATA_DIR/new.c m.c &&
  time ./a.out hop # "${@:2}"
fi

# $CC -g -fno-objc-arc -o m -I$TOCCATA_DIR -std=c99 -DCHECK_MEM_LEAK=1 $TOCCATA_DIR/core.c m.c -lpthread -latomic && ./m
# $CC -g -fno-objc-arc -o new-toc -I$TOCCATA_DIR -std=c99 -DCHECK_MEM_LEAK=1 $TOCCATA_DIR/core.c new-toc.c -lpthread
# $CC -g -fno-objc-arc -o scripter -I$TOCCATA_DIR -std=c99 -DCHECK_MEM_LEAK=1 $TOCCATA_DIR/core.c scripter.c -lpthread && ./scripter test.toc

