#! /bin/bash

clang -g -o bench -latomic -DSAFETY=1 bench.c new.c && ./bench 10 2
# clang -g -o bench -latomic -DSINGLE_THREAD=1 bench.c new.c && ./bench 5 1
# clang -g -o bench -latomic -O3 -DSINGLE_THREAD=1 bench.c new.c && ./bench 17 1
# clang -g -o bench -latomic -O3 -DSINGLE_THREAD=1 bench.c new.c && ./bench 12 1