#! /bin/bash

# clang -g -o bench -latomic -DSAFETY=1 bench.c new.c && ./bench 10 1
# clang -g -o bench -latomic bench.c new.c && ./bench 10 1
clang -O3 -g -o bench -latomic bench.c new.c && ./bench 10 2
# clang -O3 -g -o bench -latomic -DSINGLE_THREAD=1 bench.c new.c && ./bench 10 1

# clang -g -o bench -latomic -DSINGLE_THREAD=1 bench.c new.c && ./bench 10 1
