#!/bin/bash

rm $1.out $1.tmp
echo "using toccata, not new-toc"
time $TOCCATA_DIR/toccata compiler.toc > compiler.toc.tmp &&
sed -i 's/maybe((FnArity/maybe((Vector/' compiler.toc.tmp &&

awk '/^#$/ { printf "#line %d \"%s\"\n", NR+1, "m.c"; next; } { print; }' compiler.toc.tmp > m.c &&
time $CC -g -o compiler.toc.out -I$TOCCATA_DIR -std=c99 \
     -DCHECK_MEM_LEAK=1 \
     -DWAIT_FOR_LINGERING=1 \
     $TOCCATA_DIR/core.c m.c \
     -lpthread -latomic &&
time ./compiler.toc.out "$1" > q.c &&
clang-format q.c > t.c
time $CC -g -I$TOCCATA_DIR -std=c99 \
     -DCHECK_MEM_LEAK=1 \
     $TOCCATA_DIR/runtime.c t.c \
     -lpthread -latomic &&
./a.out
