#!/bin/bash

set -e

./run3 regression-tests/test1.toc party-pooper &&
./run3 regression-tests/test2.toc &&
./run3 regression-tests/test3.toc &&
./run3 regression-tests/test4.toc &&
./run3 regression-tests/test5.toc &&
./run3 regression-tests/test6.toc &&
./run3 regression-tests/test7.toc &&
./run3 regression-tests/test8.toc &&
./run3 regression-tests/test9.toc &&
./run3 regression-tests/test10.toc &&
./run3 regression-tests/test11.toc &&
./run3 regression-tests/test12.toc &&
./run3 regression-tests/test13.toc &&
./run3 regression-tests/test14.toc &&
./run3 regression-tests/test15.toc &&
./run3 regression-tests/test16.toc &&
./run3 regression-tests/test17.toc &&
./run3 regression-tests/test18.toc &&
./run3 regression-tests/test19.toc &&
./run3 regression-tests/test20.toc &&
./run3 regression-tests/test21.toc &&
./run3 regression-tests/comment-in-deftype.toc &&
./run3 regression-tests/test-global-empty-list.toc &&
./run3 regression-tests/test-ignore-inferred.toc &&
./run3 regression-tests/cond-expr-1.toc &&
./run3 regression-tests/cond-expr-2.toc &&
./run3 regression-tests/cond-expr-3.toc &&
./run3 regression-tests/cond-expr-4.toc
./run3 regression-tests/free-static-value.toc
./run3 regression-tests/tail-cond-1.toc
./run3 regression-tests/test-inline-namespaced-sym.toc

# ./run3 regression-tests/test-gensym.toc
# regression-tests/and-prop.toc
# regression-tests/check-bad-incRef.toc
# regression-tests/destruct-test.toc
# regression-tests/function-regressions.toc
# regression-tests/hash-map-regressions.toc
# regression-tests/integer-regressions.toc
# regression-tests/interpreter-test.toc
# regression-tests/lazy-list-regressions.toc
# regression-tests/or-and-constraints.toc
# regression-tests/maybe-regressions.toc
# regression-tests/state-error1-1.toc
# regression-tests/state-error1-2.toc
# regression-tests/string-regressions.toc
# regression-tests/test-apply-constructor.toc
# regression-tests/test-comment-in-let.toc
# regression-tests/test-cond.toc
# regression-tests/test-either.toc
# regression-tests/test-for.toc
# regression-tests/test-inlined-result-constraint.toc
# regression-tests/test-inline-invoke.toc
# regression-tests/test-inline-sym-literal.toc
# regression-tests/test-or-comment.toc
# regression-tests/test-parser-efficience.toc
# regression-tests/test-proto-def-constraints.toc
# regression-tests/test-proto-impl-destruct.toc
# regression-tests/test-recursive-map-fn.toc
# regression-tests/test-regressions.toc
# regression-tests/test-tail-recur-1.toc
# regression-tests/test-tail-recur-2.toc
# regression-tests/test-tail-recur-3.toc
# regression-tests/test-threading.toc
# regression-tests/test-trailing-comment.toc
# regression-tests/test-underscore-inline.toc
# regression-tests/test-uni.toc
# regression-tests/types-regressions.toc
# regression-tests/vector-regressions.toc
# regression-tests/use-before-defined.toc

echo "all done"
