#!/bin/bash

$TOCCATA_DIR/new-toc $1 > $1.c
if [ $? -ne 0 ]
then
    echo "FAIL!!" $1
    rm $1.c
    exit
else
    $CC -g -fno-objc-arc -o $1.out -I$TOCCATA_DIR -std=c99 -DCHECK_MEM_LEAK=1 $TOCCATA_DIR/core.c $1.c\
	-latomic -lpthread &&
    rm $1.c &&
    ./$1.out > /dev/null &&	
    if [ $? -ne 1 ]
    then
	echo "FAIL!!" $1
	rm $1.out
	exit
    fi
    rm $1.out
fi
