#!/bin/bash

echo "testing $1"
$TOCCATA_DIR/new-toc $1 > /dev/null
if [ $? -eq 0 ]
then
    echo
    echo "FAIL!!" $1
    echo
    echo "# $1" >> /home/jim/toccata/failures
    exit 1
else
    exit 0
fi
