#!/bin/bash

set -e

./run3 regression-tests/test1.toc party-pooper &&
./run3 regression-tests/test2.toc &&
./run3 regression-tests/test3.toc &&
./run3 regression-tests/test4.toc &&
./run3 regression-tests/test5.toc &&
./run3 regression-tests/test6.toc &&
./run3 regression-tests/test7.toc &&
./run3 regression-tests/test8.toc &&
./run3 regression-tests/test9.toc &&
./run3 regression-tests/test10.toc &&
./run3 regression-tests/test11.toc &&
./run3 regression-tests/test12.toc &&
./run3 regression-tests/test13.toc &&
./run3 regression-tests/test14.toc &&
./run3 regression-tests/test15.toc &&
./run3 regression-tests/test16.toc &&
./run3 regression-tests/test17.toc &&
./run3 regression-tests/test18.toc &&
# ./run3 regression-tests/test19.toc &&
# ./run3 regression-tests/test20.toc &&
# ./run3 regression-tests/test21.toc &&
./run3 regression-tests/comment-in-deftype.toc &&
./run3 regression-tests/test-global-empty-list.toc &&
./run3 regression-tests/test-ignore-inferred.toc &&
./run3 regression-tests/cond-expr-1.toc &&
./run3 regression-tests/cond-expr-2.toc &&
./run3 regression-tests/cond-expr-3.toc &&
./run3 regression-tests/cond-expr-4.toc &&
./run3 regression-tests/free-static-value.toc &&
./run3 regression-tests/tail-cond-1.toc &&
./run3 regression-tests/test-inline-namespaced-sym.toc &&
./run3 regression-tests/vector-regressions.toc

echo "all done"

# and-prop.toc
# check-bad-incRef.toc
# cond-expr-5.toc
# destruct-test.toc
# free-static-value.toc.tmp
# function-regressions.toc
# hash-map-regressions.toc
# integer-regressions.toc
# interpreter-test.toc
# lazy-list-regressions.toc
# list-regressions.toc
# maybe-regressions.toc
# minimal-variadic-params.toc
# or-and-constraints.toc
# promise-regressions.toc
# regression-tester.toc
# state-error1-1.toc
# state-error1-2.toc
# string-regressions.toc
# symbol-regressions.toc
# test-apply-constructor.toc
# test-comment-in-let.toc
# test-cond.toc
# test-def-empty.test
# test-either.toc
# test-for.toc
# test-gensym.toc
# test-hlist-cons.toc
# test-inlined-result-constraint.toc
# test-inline-invoke.toc
# test-inline-sym-literal.toc
# test-or-comment.toc
# test-parser-efficience.toc
# test-proto-def-constraints.toc
# test-proto-impl-destruct.toc
# test-recursive-map-fn.toc
# test-regressions.toc
# test-tail-recur-1.toc
# test-tail-recur-2.toc
# test-tail-recur-3.toc
# test-threading.toc
# test-trailing-comment.toc
# test-type-of-tail.toc
# test-underscore-inline.toc
# test-uni.toc
# types-regressions.toc
# use-before-defined.toc
# 
