#!/bin/bash

set -e

# $CC -O3 -g -fno-objc-arc -std=c99 -c core.c

# $CC -O3 -g -fno-objc-arc -o toccata -std=c99 core.o toccata.c -lpthread 

for file in regression-tests/test*.toc
do
   echo
   echo "testing" $file
   ./test-regression $file
done

for file in assertion-tests/*.toc
do
   echo
   echo "testing" $file
   ./test-assertion $file
done

for file in runtime-tests/*.toc
do
   echo
   echo "testing" $file
   ./test-runtime-check $file
done

# time `./toccata toccata.toc > toccata.c`
# $CC -O3 -g -fno-objc-arc -o toccata -std=c99 core.o toccata.c -lpthread

# time `./toccata toccata.toc > toccata.c`
# $CC -O3 -g -fno-objc-arc -o toccata -std=c99 core.o toccata.c -lpthread

echo "Regressions pass"
