#!/bin/bash

set -e

# $CC -O3 -g -fno-objc-arc -std=c99 -c core.c &&

# git checkout toccata.c &&
# $CC -O3 -g -fno-objc-arc -o toccata -std=c99 core.c toccata.c -lpthread &&

# echo &&
# echo "restored" &&
# echo &&

time `./toccata toccata.toc > new-toc.tmp` &&
awk '/^#$/ { printf "#line %d \"%s\"\n", NR+1, "new-toc.c"; next; } { print; }' new-toc.tmp > new-toc.c &&
$CC -O3 -g -fno-objc-arc -o new-toc -std=c99 core.c new-toc.c -lpthread &&

echo &&
echo "compiled" &&
echo &&

# test-regression regression-tests/test-regressions.toc &&

# run test.toc &&

# $TOCCATA_DIR/new-toc scripter.toc > m.tmp &&
# awk '/^#$/ { printf "#line %d \"%s\"\n", NR+1, "m.c"; next; } { print; }' m.tmp > m.c &&
# $CC -g -fno-objc-arc -DCHECK_MEM_LEAK=1 -o m -std=c99 core.c m.c -lpthread &&
# ./m deps-graph.toc &&

for file in regression-tests/test*.toc
do
   echo
   echo "testing" $file
   ./test-regression $file
done &&

for file in assertion-tests/*.toc
do
   echo
   # echo "testing" $file
   ./test-assertion $file
done &&

for file in runtime-tests/*.toc
do
   echo
   echo "testing" $file
   ./test-runtime-check $file
done &&

time `./new-toc toccata.toc > new-toc.tmp` &&
awk '/^#$/ { printf "#line %d \"%s\"\n", NR+1, "new-toc.c"; next; } { print; }' new-toc.tmp > new-toc.c &&
$CC -O3 -g -fno-objc-arc -o new-toc -std=c99 core.c new-toc.c -lpthread &&

echo &&
echo "re-compiled" &&
echo &&

time `./new-toc toccata.toc > new-toc.tmp` &&
awk '/^#$/ { printf "#line %d \"%s\"\n", NR+1, "new-toc.c"; next; } { print; }' new-toc.tmp > new-toc.c &&
$CC -O3 -g -fno-objc-arc -o new-toc -std=c99 core.c new-toc.c -lpthread &&

echo "Regressions pass"
