#!/bin/bash

set -e

for file in `grep -R --include=*.toc -l $1`
do
    echo $file &&
    sed -i "s/$1/$2/" $file
done

# TODO: someday make this work
# find -L . -depth -type d -name "$1" -exec mv {} "../$2" \;
